export enum TX_KEY {
  CREATE_JOB = 'TX:CREATE_JOB',
  EDIT_JOB = 'TX:EDIT_JOB',
  CANCEL_JOB = 'TX:CANCEL_JOB',
  EXECUTE_JOB = 'TX:EXECUTE_JOB',
  // STAKE_WARP = 'TX:STAKE_WARP',
  ADD_FUNDS = 'TX:ADD_FUNDS',
  WITHDRAW_FUNDS = 'TX:WITHDRAW_FUNDS',
  CREATE_ACCOUNT = 'TX:CREATE_ACCOUNT',
  CREATE_TEMPLATE = 'TX:CREATE_TEMPLATE',
  EDIT_TEMPLATE = 'TX:EDIT_TEMPLATE',
  DELETE_TEMPLATE = 'TX:DELETE_TEMPLATE',
  CREATE_FUNDING_ACCOUNT = 'TX:CREATE_FUNDING_ACCOUNT',
}
